/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEWS;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import sistemacadastramentoeavaliacaodeeventos.ConexaBD;

/**
 *
 * @author Fortunato José
 */
public class Participar extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public Participar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpParticipar1 = new javax.swing.JPanel();
        jpParticipar2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNomp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Nome1 = new javax.swing.JTextField();
        txtSobrenomeP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCategoriaP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnRegistar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setClosable(true);
        setToolTipText("");
        setMinimumSize(new java.awt.Dimension(0, 0));
        setName(""); // NOI18N
        setOpaque(true);
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpParticipar1.setBackground(new java.awt.Color(255, 255, 255));
        jpParticipar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpParticipar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpParticipar2.setBackground(new java.awt.Color(0, 0, 102));
        jpParticipar2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("Nome:");
        jpParticipar2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));
        jpParticipar2.add(txtNomp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 260, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 255));
        jLabel4.setText("ID Evento:");
        jpParticipar2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txt_Nome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Nome1ActionPerformed(evt);
            }
        });
        jpParticipar2.add(txt_Nome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 60, -1));
        jpParticipar2.add(txtSobrenomeP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 260, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 255));
        jLabel5.setText("Sobrenome:");
        jpParticipar2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        jpParticipar2.add(txtCategoriaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 260, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 255));
        jLabel6.setText("Categoria:");
        jpParticipar2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 20));

        btnRegistar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegistar.setForeground(new java.awt.Color(51, 153, 255));
        btnRegistar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/Save.png"))); // NOI18N
        btnRegistar.setText("REGISTAR");
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });
        jpParticipar2.add(btnRegistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        btnLimpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(51, 153, 255));
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/Redo.png"))); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jpParticipar2.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        jpParticipar1.add(jpParticipar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 396, 300));

        getContentPane().add(jpParticipar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 417, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Nome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Nome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Nome1ActionPerformed

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed
        // TODO add your handling code here:

        try {

            Connection con = ConexaBD.ligar();
            String inserir = "INSERT INTO partcipante(Nome, Sobrenome, Categoria, )"
            + " values (?,?,?)";
            PreparedStatement ps = con.prepareStatement(inserir);
            ps.setString(1, txtNomp.getText());
            ps.setString(2, txtSobrenomeP.getText());
            ps.setString(3, txtCategoriaP.getText());
            ps.execute();
            ps.close();
            con.close();

            JOptionPane.showMessageDialog(null, "PARTIPANTE REGISTADO");
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }//GEN-LAST:event_btnRegistarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:

        txtNomp.setText("");
        txtSobrenomeP.setText("");
        txtCategoriaP.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRegistar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jpParticipar1;
    private javax.swing.JPanel jpParticipar2;
    private javax.swing.JTextField txtCategoriaP;
    private javax.swing.JTextField txtNomp;
    private javax.swing.JTextField txtSobrenomeP;
    private javax.swing.JTextField txt_Nome1;
    // End of variables declaration//GEN-END:variables
}
