/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEWS;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import sistemacadastramentoeavaliacaodeeventos.ConexaBD;

/**
 *
 * @author Fortunato José
 */
public final class TelaHome extends javax.swing.JFrame {

    /**
     * Creates new form TelaHome
     */
    public TelaHome() {
        //else jMenuItem6.setVisible(true);
        initComponents();
        CarreagarTable();
        jbtnEditarevento.setEnabled(false);
        jbtnEliminarEvento.setEnabled(false);
    }

    private int BuscarIDAmbiente(String Espaco) {
        Connection conect = ConexaBD.ligar();
        String sql = String.format("SELECT IdAmbiente FROM ambiente WHERE espacoFisico = '%s'", Espaco);
        try ( Statement stmt = conect.createStatement()) {
            stmt.execute(sql);
            try ( ResultSet rs = stmt.executeQuery(sql)) {
                rs.next();
                return rs.getInt(1);
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
            return 0;
        }
    }

    private void CarreagarTable() {
        Object[] columnNames = {"ID", "Nome", "N Lugares", "Data de Evento", "Avaliacao", "Hora do Inicio", "Hora do Fim", "Descricao", "Duracao","Tipo de Evento","Lugar Fisico", "Funcionario"};
        Object[] lista = new Object[15];
        DefaultTableModel tbModelF = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };
        tbModelF.setColumnIdentifiers(columnNames);

        Connection conect = ConexaBD.ligar();
        String sql = String.format("call gestao_de_eventos.MostrarEventos()");
        try ( Statement stmt = conect.createStatement()) {
            stmt.execute(sql);
            try ( ResultSet rs = stmt.executeQuery(sql)) {
                while (rs.next()) {
                    lista[0] = (rs.getString("idEvento"));
                    lista[1] = (rs.getString("NomeEvento"));
                    lista[2] = (rs.getString("numLugares"));
                    lista[3] = (rs.getString("DataEvento"));
                    lista[4] = (rs.getString("Avaliacao"));
                    lista[5] = (rs.getString("inicioEvento"));
                    lista[6] = (rs.getString("fimEvento"));
                    lista[7] = (rs.getString("Descrissao"));
                    lista[8] = (rs.getString("duracao"));
                    lista[9] = (rs.getString("tipo"));
                    lista[10] = (rs.getString("espacoFisico"));
                    lista[11] = (rs.getString("nome"));
                    tbModelF.addRow(lista);
                }
                tblEventos.setModel(tbModelF);
            }

        } catch (SQLException ex) {
            ex.printStackTrace();

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlhora = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEventos = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jbtnEditarevento = new javax.swing.JToggleButton();
        jbtnEliminarEvento = new javax.swing.JToggleButton();
        jbtnGerirAbt = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_NomeEvento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbTipoDeEventos = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbEspacoFisico = new javax.swing.JComboBox<>();
        txt_Duracao = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtInicio = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtFim = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_descrissao = new javax.swing.JTextField();
        txtDataEvento = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        JbtnSalvar = new javax.swing.JButton();
        lbtnLimpar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuHome = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jItemFechar = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("Valdhir André");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 204));
        jLabel4.setText("Nivel:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 204));
        jLabel5.setText("Usuario");

        jlhora.setBackground(new java.awt.Color(255, 255, 255));
        jlhora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlhora.setForeground(new java.awt.Color(0, 153, 204));
        jlhora.setText("23:26");

        labelData.setBackground(new java.awt.Color(255, 255, 255));
        labelData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelData.setForeground(new java.awt.Color(0, 153, 204));
        labelData.setText("Data");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(81, 81, 81)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 334, Short.MAX_VALUE)
                .addComponent(jlhora)
                .addGap(30, 30, 30)
                .addComponent(labelData)
                .addGap(69, 69, 69))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jlhora)
                    .addComponent(labelData))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        tblEventos.setAutoCreateRowSorter(true);
        tblEventos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Nº Lugares", "Data do Evento", "Descricao", "Avaliação", "Tipo", "Inicio", "Fim", "Usuario"
            }
        ));
        tblEventos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblEventos.setDropMode(javax.swing.DropMode.INSERT_ROWS);
        tblEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEventosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEventos);
        if (tblEventos.getColumnModel().getColumnCount() > 0) {
            tblEventos.getColumnModel().getColumn(0).setResizable(false);
            tblEventos.getColumnModel().getColumn(0).setHeaderValue("Id");
            tblEventos.getColumnModel().getColumn(1).setHeaderValue("Nome");
            tblEventos.getColumnModel().getColumn(2).setHeaderValue("Nº Lugares");
            tblEventos.getColumnModel().getColumn(3).setHeaderValue("Data do Evento");
            tblEventos.getColumnModel().getColumn(4).setHeaderValue("Descricao");
            tblEventos.getColumnModel().getColumn(5).setHeaderValue("Avaliação");
            tblEventos.getColumnModel().getColumn(6).setHeaderValue("Tipo");
            tblEventos.getColumnModel().getColumn(7).setHeaderValue("Inicio");
            tblEventos.getColumnModel().getColumn(8).setHeaderValue("Fim");
            tblEventos.getColumnModel().getColumn(9).setResizable(false);
            tblEventos.getColumnModel().getColumn(9).setHeaderValue("Usuario");
        }

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 255));
        jLabel8.setText("EVENTOS MARCADOS");

        jbtnEditarevento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnEditarevento.setForeground(new java.awt.Color(0, 153, 255));
        jbtnEditarevento.setText("EDITAR");
        jbtnEditarevento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditareventoActionPerformed(evt);
            }
        });

        jbtnEliminarEvento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnEliminarEvento.setForeground(new java.awt.Color(0, 153, 255));
        jbtnEliminarEvento.setText("ELIMINAR");
        jbtnEliminarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarEventoActionPerformed(evt);
            }
        });

        jbtnGerirAbt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnGerirAbt.setForeground(new java.awt.Color(0, 153, 255));
        jbtnGerirAbt.setText("AMBIENTE");

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 255));
        jLabel6.setText("Nome do evento ");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        jPanel3.add(txt_NomeEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 280, 22));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 153, 255));
        jLabel7.setText("Data");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, -1, -1));

        cbTipoDeEventos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbTipoDeEventos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prensencial", "Virtual" }));
        cbTipoDeEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoDeEventosActionPerformed(evt);
            }
        });
        jPanel3.add(cbTipoDeEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 153, 255));
        jLabel9.setText("Tipo de Evento");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 153, 255));
        jLabel10.setText("Espaço Físico");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        cbEspacoFisico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbEspacoFisico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auditório", "Multifunções", "Pátio", "Sala de Aula", "Outro" }));
        cbEspacoFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEspacoFisicoActionPerformed(evt);
            }
        });
        jPanel3.add(cbEspacoFisico, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 118, -1));

        txt_Duracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DuracaoActionPerformed(evt);
            }
        });
        jPanel3.add(txt_Duracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 100, 22));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 255));
        jLabel12.setText("Duração");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, 20));

        txtInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInicioActionPerformed(evt);
            }
        });
        jPanel3.add(txtInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 90, 22));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 153, 255));
        jLabel14.setText("Início");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 40, 20));

        txtFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFimActionPerformed(evt);
            }
        });
        jPanel3.add(txtFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 70, 22));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 153, 255));
        jLabel15.setText("Descrição");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        jPanel3.add(txt_descrissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 174, 80));
        jPanel3.add(txtDataEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 130, 22));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 153, 255));
        jLabel18.setText("Fim");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel3.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 265, 22));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 153, 255));
        jLabel16.setText("Cadastrado Por");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        JbtnSalvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JbtnSalvar.setForeground(new java.awt.Color(51, 153, 255));
        JbtnSalvar.setText("SALVAR");
        JbtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnSalvarActionPerformed(evt);
            }
        });

        lbtnLimpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbtnLimpar.setForeground(new java.awt.Color(51, 153, 255));
        lbtnLimpar.setText("LIMPAR");
        lbtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbtnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(JbtnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnEliminarEvento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnGerirAbt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnEditarevento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbtnLimpar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnGerirAbt)
                            .addComponent(jbtnEditarevento)
                            .addComponent(jbtnEliminarEvento)
                            .addComponent(JbtnSalvar)
                            .addComponent(lbtnLimpar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jMenuHome.setText("Home");
        jMenuHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHomeActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuHome);

        jMenu4.setText("Ajuda");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setText("Help");
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Fechar");

        jItemFechar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jItemFechar.setText("Fechar");
        jItemFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemFecharActionPerformed(evt);
            }
        });
        jMenu5.add(jItemFechar);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1057, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHomeActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jMenuHomeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //buscar Data
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        labelData.setText(formatador.format(data));

//       Timer time = new Timer(1000, hora());
//       time.start();
    }//GEN-LAST:event_formWindowOpened

    private void jItemFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemFecharActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jItemFecharActionPerformed

    private void lbtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbtnLimparActionPerformed
        // TODO add your handling code here:
        txt_NomeEvento.setText("");
        //        txt_usuario.setText("");
        txt_Duracao.setText("");
        txtInicio.setText("");
        txtFim.setText("");
        txt_descrissao.setText("");
        cbEspacoFisico.setSelectedIndex(-1);
        cbTipoDeEventos.setSelectedIndex(-1);
        //txt_DChooserData.setDate(null);
    }//GEN-LAST:event_lbtnLimparActionPerformed

    private void JbtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnSalvarActionPerformed

        Connection con = ConexaBD.ligar();

        try {

            String inserir = "INSERT INTO evento (NomeEvento, DataEvento, Descrissao, Duracao, tipo, fimEvento, inicioEvento, ambienteFK) "
                    + "values (?,?,?,?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(inserir);
            ps.setString(1, txt_NomeEvento.getText());
            ps.setString(2, txtDataEvento.getText());
            ps.setString(3, txt_descrissao.getText());
            ps.setString(4, txt_Duracao.getText());
            ps.setString(5, cbTipoDeEventos.getSelectedItem() + "");
            ps.setString(6, txtFim.getText());
            ps.setString(7, txtInicio.getText());
            if (cbTipoDeEventos.getSelectedItem().equals("Virtual")) {
               ps.setInt(8, BuscarIDAmbiente("Nenhum")); 
            }else ps.setInt(8, BuscarIDAmbiente(cbEspacoFisico.getSelectedItem().toString()));
            ps.execute();
            CarreagarTable();

            //ps.setString(8, txt_usuario.getText());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }

//        try {
//
//            String inserir = "INSERT INTO ambiente ( espacoFisico, numLugares) values (?,?)";
//            PreparedStatement ps = con.prepareStatement(inserir);
//            ps.setString(1, cbEspacoFisico.getSelectedItem() + "");
////            ps.setString(2, txt_NumLugares.getText());
//            ps.execute();
//            ps.close();
//            con.close();
//
//        } catch (SQLException ex) {
//            ex.printStackTrace();
//        }

        JOptionPane.showMessageDialog(null, "EVENTO MARCADO");
    }//GEN-LAST:event_JbtnSalvarActionPerformed

    private void txtFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFimActionPerformed

    private void txtInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInicioActionPerformed

    private void txt_DuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DuracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DuracaoActionPerformed

    private void cbEspacoFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEspacoFisicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEspacoFisicoActionPerformed

    private void cbTipoDeEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoDeEventosActionPerformed
        // TODO add your handling code here:
        if (cbTipoDeEventos.getSelectedItem().equals("Virtual")) {
            cbEspacoFisico.setEnabled(false);
        }else cbEspacoFisico.setEnabled(true);
    }//GEN-LAST:event_cbTipoDeEventosActionPerformed

    private void tblEventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEventosMouseClicked
        // TODO add your handling code here:
        jbtnEliminarEvento.setEnabled(true);
        jbtnEditarevento.setEnabled(false);
        if (evt.getClickCount() == 2) {
            int row = tblEventos.getSelectedRow();
            TableModel model = tblEventos.getModel();
            
            txt_NomeEvento.setText((model.getValueAt(row, 1).toString()));
            txtDataEvento.setText(model.getValueAt(row, 3).toString());
            txtInicio.setText((model.getValueAt(row, 5).toString()));
            txtFim.setText(model.getValueAt(row, 6).toString());
            txt_Duracao.setText(model.getValueAt(row, 8).toString());
            txtUsuario.setText(model.getValueAt(row, 11).toString());
            txt_descrissao.setText(model.getValueAt(row, 7).toString());
            cbEspacoFisico.setSelectedItem(model.getValueAt(row, 10).toString());
            cbTipoDeEventos.setSelectedItem(model.getValueAt(row, 9).toString());
            txtUsuario.setEnabled(false);
            jbtnEditarevento.setEnabled(true);
            if (tblEventos.getSelectedRow() != -1) {
                jbtnEliminarEvento.setEnabled(false);
            }
            JbtnSalvar.setEnabled(false);
        }

    }//GEN-LAST:event_tblEventosMouseClicked

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void jbtnEliminarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarEventoActionPerformed
        // TODO add your handling code here:
        Connection con = ConexaBD.ligar();

        try {
            int row = tblEventos.getSelectedRow();
            TableModel model = tblEventos.getModel();

            String delete = "DELETE FROM evento WHERE idEvento = ?";
            PreparedStatement ps = con.prepareStatement(delete);
            ps.setInt(1, Integer.parseInt(model.getValueAt(row, 0).toString()));
            ps.execute();
            
            CarreagarTable();

            //ps.setString(8, txt_usuario.getText());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }//GEN-LAST:event_jbtnEliminarEventoActionPerformed

    private void jbtnEditareventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditareventoActionPerformed
        // TODO add your handling code here:

        Connection con = ConexaBD.ligar();
        int row = tblEventos.getSelectedRow();
        TableModel model = tblEventos.getModel();

        try {

            String ACt = "UPDATE evento SET NomeEvento = ? , DataEvento = ?, Descrissao = ?, Duracao = ?, tipo = ?, fimEvento = ?, inicioEvento = ?, ambienteFK = ? "
                    + "WHERE idEvento = ?";
            PreparedStatement ps = con.prepareStatement(ACt);
            ps.setString(1, txt_NomeEvento.getText());
            ps.setString(2, txtDataEvento.getText());
            ps.setString(3, txt_descrissao.getText());
            ps.setString(4, txt_Duracao.getText());
            ps.setString(5, cbTipoDeEventos.getSelectedItem() + "");
            ps.setString(6, txtFim.getText());
            ps.setString(7, txtInicio.getText());
            ps.setInt(8, BuscarIDAmbiente(cbEspacoFisico.getSelectedItem().toString()));
            ps.setInt(9, Integer.parseInt(model.getValueAt(row, 0).toString()));
            ps.execute();
            CarreagarTable();

        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        txt_NomeEvento.setText("");
        txtDataEvento.setText("");
        txtInicio.setText("");
        txtFim.setText("");
        txt_Duracao.setText("");
        txtUsuario.setText("");
        txt_descrissao.setText("");


    }//GEN-LAST:event_jbtnEditareventoActionPerformed

    public static void main(String[] args) {

        TelaHome t = new TelaHome();
        t.setVisible(true);

    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JbtnSalvar;
    public javax.swing.JComboBox<String> cbEspacoFisico;
    public javax.swing.JComboBox<String> cbTipoDeEventos;
    public com.toedter.calendar.JDateChooser jDateChooser1;
    public javax.swing.JMenuItem jItemFechar;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JMenu jMenu4;
    public javax.swing.JMenu jMenu5;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenu jMenuHome;
    public javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JPasswordField jPasswordField1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JToggleButton jbtnEditarevento;
    public javax.swing.JToggleButton jbtnEliminarEvento;
    public javax.swing.JButton jbtnGerirAbt;
    public javax.swing.JLabel jlhora;
    public javax.swing.JLabel labelData;
    public javax.swing.JButton lbtnLimpar;
    public javax.swing.JTable tblEventos;
    public javax.swing.JTextField txtDataEvento;
    public javax.swing.JTextField txtFim;
    public javax.swing.JTextField txtInicio;
    public javax.swing.JTextField txtUsuario;
    public javax.swing.JTextField txt_Duracao;
    public javax.swing.JTextField txt_NomeEvento;
    public javax.swing.JTextField txt_descrissao;
    // End of variables declaration//GEN-END:variables

//class hora implements ActionListener {
//@Override
//public void actionPerfomed(ActionEvent e) {
//Calendar now = Calendar.getInstance();
//jlhora.setText(String.format("%1$H:%1$M:%1$S", now));
//     }
//    }
} //fim class principal
